apiVersion: apps/v1
kind: Deployment
metadata:
  name: troubleshooting
  labels:
    app: troubleshooting
spec:
  replicas: 0
  selector:
    matchLabels:
      app: troubleshooting
  template:
    metadata:
      labels:
        app: troubleshooting
    spec:
      containers:
      - name: troubleshooting
        image: nginxx:1.19.7-alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "8Mi"
            cpu: "50m"
          limits:
            memory: "16Mi"
            cpu: "100m"
        command: ['/bin/sh', 'pause']
---
apiVersion: v1
kind: Service
metadata:
  name: troubleshooting
spec:
  selector:
    app: troubleshooting-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: troubleshooting
spec:
  host: ""
  to:
    kind: Service
    name: troubleshooting-service
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None
---
apiVersion: v1
metadata:
  name: netshoot
kind: Pod
spec:
  containers:
  - name: netshoot
    image: nicolaka/netshoot
    command: ["sleep"]
    args: ["3600"]
    imagePullPolicy: Always
    securityContext:
      capabilities:
        add: ["NET_BIND_SERVICE"]
