apiVersion: apps/v1
kind: Deployment
metadata:
  name: troubleshooting
  labels:
    app: troubleshooting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: troubleshooting
  template:
    metadata:
      labels:
        app: troubleshooting
    spec:
      containers:
      - name: troubleshooting
        image: nginx:1.19.7-alpine
        ports:
        - name: http
          containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: troubleshooting
spec:
  selector:
    app: troubleshooting
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: troubleshooting
spec:
  rules:
  - host: ""
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: troubleshooting
            port:
              number: 80
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: troubleshooting
spec:
  host: ""
  to:
    kind: Service
    name: troubleshooting
    weight: 100
  port:
    targetPort: 80
  wildcardPolicy: None